application: qrwrapper
version: 7
runtime: python
api_version: 1

handlers:

- url: /images
  static_dir: images

- url: /vc
  script: vcardhandler.py

- url: /qr
  script: qrhandler.py

- url: /css_never_gonna_happen
  script: csshelper.py

- url: /rr
  script: rrhandler.py

- url: /bz
  script: bizcardhandler.py

- url: /emsg
  script: emailhandler.py

- url: /wifi
  script: wifihandler.py

- url: /.*
  script: main.py

